#!/bin/sh
# Removes 'Microsoft Remote Desktop.app' if 'Windows App.app' is installed.

set -u

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

install_dir="${3:-/}/Applications"
windows_app="Windows App.app"
microsoft_remote_desktop_app="Microsoft Remote Desktop.app"
microsoft_remote_desktop_process="Microsoft Remote Desktop"

if [ ! -d "${install_dir}/${microsoft_remote_desktop_app}" ]; then
	echo "'${microsoft_remote_desktop_app}' not found. Nothing to remove."
	exit 0
fi

if [ ! -d "${install_dir}/${windows_app}" ]; then
	echo "'${microsoft_remote_desktop_app}' not removed because '${windows_app}' is missing."
	exit 1
fi

pkill -x "${microsoft_remote_desktop_process}"
rm -rf "${install_dir:?}/${microsoft_remote_desktop_app}"
echo "'${microsoft_remote_desktop_app}' successfully removed."
exit 0
